plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    testImplementation libs.junit

    implementation libs.guava
    api 'com.microsoft.kiota:microsoft-kiota-abstractions:1.8.4'
    api 'com.microsoft.kiota:microsoft-kiota-http-okHttp:1.8.4'
    implementation 'com.microsoft.kiota:microsoft-kiota-serialization-text:1.8.4'
    implementation 'com.microsoft.kiota:microsoft-kiota-serialization-form:1.8.4'
    implementation 'com.microsoft.kiota:microsoft-kiota-serialization-multipart:1.8.4'
    implementation 'io.kiota:kiota-serialization-jackson:0.0.21' // Replaces com.microsoft.kiota:microsoft-kiota-serialization-json
    implementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
